from fastapi import FastAPI, Depends
from fastapi.testclient import TestClient
from utils.protected import decode_token

app = FastAPI()

@app.post("/test-decode")
def test_decode(token: str):
    return decode_token(token)

client = TestClient(app)

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy5sZXh0b3JhaC1lbGVhcm5pbmcuY29tL2FwL2xhcmF2ZWwvYXBpL2FpdHV0b3ItbG9naW4iLCJpYXQiOjE3NzE2MDEzNjgsImV4cCI6MTc3MTYwNDk2OCwibmJmIjoxNzcxNjAxMzY4LCJqdGkiOiJmVUxNbUtocmQ5QkkwYVZwIiwic3ViIjoiMTE2OCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJpZCI6MTE2OCwic3R1ZGVudF9pZCI6IkxUUi8yMDIyLzA0NTcyNiIsInRpdGxlIjpudWxsLCJzdXJuYW1lIjoiQkFUIiwiZmlyc3RfbmFtZSI6IkJBVCIsIm90aGVyX25hbWUiOm51bGwsImVtYWlsIjoibWVyY3lidGF5bG9yQHlhaG9vLmNvbSIsInBob25lX251bWJlciI6IjA4MDkxMjM0NTY3IiwidXNlcl9sZXZlbCI6IjAiLCJjb3Vyc2UiOiJJRUxUUyIsInJlZ19ieSI6IlNlbGYiLCJjb3VudHJ5IjpudWxsLCJ0b3duIjpudWxsLCJhZGRyZXNzIjpudWxsLCJwYXNzcG9ydCI6bnVsbCwiYWRkcmVzczIiOm51bGwsImhlYXJfdXMiOm51bGx9.g2R6UEczAuGFOFx3K9nlmlCckVkcyZJyFXbs7LCyT_E"

response = client.post(f"/test-decode?token={token}")
print("Status:", response.status_code)
print("Response:", response.json())
