SUBJECT_MAPPING = {
  "FRE": "French Language",
  "GER": "German Language",
  "SPA": "Spanish Language",
  "ENG": "English Language",
  "CHI": "Chinese (HSK)",
  "POR": "Portuguese Language",
  "ITA": "Italian Language",
  "RUS": "Russian Language",
  "JAP": "Japanese Language",
  "KOR": "Korean Language",
  "YOR": "Yoruba Language",
  "HAU": "Hausa Language",
  "IGB": "Igbo Language",
  "GRE": "GRE",
  "IEL": "IELTS",
  "TOE": "TOEFL",
  "SAT": "SAT",
  "TUR": "Turkish Language",
  "HEB": "Hebrew Language",
  "POL": "Polish Language",
  "HIN": "Hindi Language",
  "FIN": "Finnish Language",
  "DUT": "Dutch Language",
  "BUS": "Business English",
  "EVE": "Evening Classes",
  "OET": "OET Prep",
  "SEL": "SELT",
  "ESO": "ESOL",
  "DUO": "Duolingo",
  "PTE": "PTE",
  "CEL": "CELPIP",
  "GMA": "GMAT"
}
